### ISSUE TITLE
Extremely large number of patches crashes server

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#110]
To reproduce, run `resize-world -400 400 -300 300`. The server will crash with:

	java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:2367)
		at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
		at java.lang.StringBuffer.append(StringBuffer.java:237)
		at java.io.StringWriter.write(StringWriter.java:101)
		at org.json4s.native.Printer$class.layout$1(Printer.scala:27)
		at org.json4s.native.Printer$class.compact(Printer.scala:35)
		at org.json4s.native.Printer$.compact(Printer.scala:13)
		at org.json4s.native.Printer$class.compact(Printer.scala:20)
		at org.json4s.native.Printer$.compact(Printer.scala:13)
		at org.json4s.native.JsonMethods$class.compact(JsonMethods.scala:56)
		at org.json4s.native.JsonMethods$.compact(JsonMethods.scala:62)
		at org.nlogo.tortoise.json.JSONSerializer$.serialize(JSONSerializer.scala:63)
		at models.remote.NetLogoController$StateManager.models$remote$NetLogoController$StateManager$$sendUpdate(NetLogoController.scala:68)
		at models.remote.NetLogoController$StateManager.models$remote$NetLogoController$StateManager$$sendPendingUpdate(NetLogoController.scala:72)
		at models.remote.NetLogoController$StateManager$$anonfun$receive$2.applyOrElse(NetLogoController.scala:89)
		at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
		at akka.actor.ActorCell.invoke(ActorCell.scala:456)
		at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
		at akka.dispatch.Mailbox.run(Mailbox.scala:219)
		at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386

I believe this is caused by the JSON serialization of the initial state of those 481401 patches. Indeed, this does not happen when running model runs on desktop NetLogo and the stack trace is inside the JSON serialization methods.

The only really robust way of fixing this that I see is to break up large diffs into multiple messages, serializing them one at a time.

Note that the problem is also triggered by models with a large number of patches, such as `test/benchmarks/CA1D Benchmark`.

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Teletortoise#2
