### ISSUE TITLE
Server crashed by user actions

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#114]
Here's the corresponding log:

> [info] 06:36:22.456 - application - Gabriel joining
> [info] 06:36:39.322 - application - "test/tortoise/Termites.nlogo" requested
> [info] 06:36:39.958 - application - Command(Gabriel,open,turtles-own [next steps]
> [info] 06:36:39.958 - application - Opening
> [info] 06:36:39.965 - application - Opening model
> [info] 06:36:40.382 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:40.383 - application - Compiling
> [info] 06:36:42.039 - application - Finished opening model
> [info] 06:36:49.801 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:49.802 - application - Compiling
> [info] 06:36:50.539 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:50.540 - application - Compiling
> [info] 06:36:52.073 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:52.074 - application - Compiling
> [info] 06:39:56.826 - application - "test/benchmarks/CA1D%20Benchmark.nlogo" requested
> [info] 06:39:58.027 - application - Command(Gabriel,open,globals
> [info] 06:39:58.027 - application - Opening
> [info] 06:39:58.027 - application - Opening model
> [info] 06:40:00.177 - application - Command(Gabriel,compile,globals
> [info] 06:40:00.178 - application - Compiling
> [info] 06:45:47.738 - application - Finished opening model
> [info] 06:46:52.755 - application - Command(You,open,globals [grass]  ;; keep track of how much grass there is
> [info] 06:46:54.313 - application - Opening
> [info] 06:46:54.339 - application - Command(You,compile,globals [grass]  ;; keep track of how much grass there is
> [info] 06:46:55.441 - application - Beginning compilation
> [ERROR] [01/11/2014 06:46:58.986] [application-akka.actor.default-dispatcher-25] [akka://application/user/$E] Timed out
> akka.pattern.AskTimeoutException: Timed out
>         at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
>         at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
>         at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:782)
>         at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:779)
>         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
>         at java.lang.Thread.run(Thread.java:722)
> 
> [info] 06:47:08.779 - application - Compiling
> [info] 06:47:08.939 - application - Beginning compilation
> [info] 06:47:11.688 - application - Command(You,open,globals [
> [info] 06:47:11.711 - application - Command(You,compile,globals [
> [info] 06:47:11.689 - application - Opening
> [info] 06:47:11.886 - application - Beginning compilation
> [ERROR] [01/11/2014 06:47:11.690] [application-akka.actor.default-dispatcher-25] [akka://application/user/$E] Futures timed out after [1 second]
> java.util.concurrent.TimeoutException: Futures timed out after [1 second]
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:96)
>         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:100)
>         at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
>         at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
>         at scala.concurrent.Await$.result(package.scala:107)
>         at models.local.LocalInstance.compile(LocalInstance.scala:66)
>         at models.core.WebInstance$$anonfun$receiveBase$1.applyOrElse(WebInstance.scala:38)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:456)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> 
> [warn] 06:47:12.350 - application - Execution failed: Nothing named GRASS? has been defined
> [info] 06:47:12.355 - application - Compilation complete
> [INFO] [01/11/2014 06:47:12.442] [application-akka.actor.default-dispatcher-19] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$G#1677652596] to Actor[akka://application/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> [info] 06:47:14.250 - application - Compiling
> [ERROR] [01/11/2014 06:47:14.249] [application-akka.actor.default-dispatcher-33] [akka://application/user/$H] Futures timed out after [1 second]
> java.util.concurrent.TimeoutException: Futures timed out after [1 second]
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:96)
>         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:100)
>         at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
>         at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
>         at scala.concurrent.Await$.result(package.scala:107)
>         at models.local.LocalInstance.open(LocalInstance.scala:71)
>         at models.core.WebInstance$$anonfun$receiveBase$1.applyOrElse(WebInstance.scala:41)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:456)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> 
> [info] 06:47:14.258 - application - Beginning compilation
> [ERROR] [01/11/2014 06:47:18.298] [application-akka.actor.default-dispatcher-25] [akka://application/user/$H] Timed out
> akka.pattern.AskTimeoutException: Timed out
>         at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
>         at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
>         at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:782)
>         at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:779)
>         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
>         at java.lang.Thread.run(Thread.java:722)
> 
> [warn] 06:47:26.178 - application - Execution failed: Nothing named ALBEDO has been defined
> [info] 06:47:26.178 - application - Compilation complete
> [INFO] [01/11/2014 06:47:26.179] [application-akka.actor.default-dispatcher-19] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$K#-1950102775] to Actor[akka://application/deadLetters] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> [info] 06:47:56.218 - application - No errors!
> [info] 06:47:56.393 - application - Compilation complete
> [info] 06:47:56.342 - application - No errors!
> [info] 06:47:56.395 - application - Compilation complete
> [INFO] [01/11/2014 06:47:56.686] [application-akka.actor.default-dispatcher-20] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$F#1166017523] to Actor[akka://application/deadLetters] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> [INFO] [01/11/2014 06:47:56.686] [application-akka.actor.default-dispatcher-20] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$I#-2119155620] to Actor[akka://application/deadLetters] was not delivered. [8] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> Killed

**Comment by TheBizzle** [comment]
This issue was moved to NetLogo/Teletortoise#1
